# Generated by Django 5.0.6 on 2024-06-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_phone_number_alter_hr_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01T12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01T12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01T12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01T12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
