# Generated by Django 5.0.6 on 2024-06-28 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_created_at_company_modified_at_and_more'),
        ('team_management', '0011_remove_shiftpattern_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='team_management.shiftpattern'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='team_management.team'),
        ),
    ]
