# Generated by Django 5.0.6 on 2024-06-26 18:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_created_at_company_modified_at_and_more'),
        ('team_management', '0002_shiftblock_working_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftblock',
            name='days_off',
        ),
        migrations.RemoveField(
            model_name='shiftblock',
            name='days_on',
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_patterns', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='shiftblock',
            name='working_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=20),
        ),
        migrations.AlterField(
            model_name='shiftpattern',
            name='rotation_weeks',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='shiftpattern',
            unique_together={('company', 'name')},
        ),
    ]
