# Generated by Django 5.0.6 on 2024-06-27 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0003_remove_shiftblock_days_off_remove_shiftblock_days_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftpattern',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='shiftpattern',
            name='is_recurring',
        ),
        migrations.AlterField(
            model_name='shiftpattern',
            name='rotation_weeks',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
    ]
