# Generated by Django 5.0.6 on 2024-06-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0004_remove_shiftpattern_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='team_management.shiftblock')),
            ],
            options={
                'unique_together': {('date', 'shift_block')},
            },
        ),
    ]
