# Generated by Django 5.0.6 on 2024-06-28 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_created_at_company_modified_at_and_more'),
        ('team_management', '0005_shiftassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftpattern',
            name='employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_patterns', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_patterns', to='accounts.manager'),
        ),
        migrations.AlterField(
            model_name='shiftpattern',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_patterns', to='accounts.company'),
        ),
    ]
