# Generated by Django 5.0.6 on 2024-06-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_created_at_company_modified_at_and_more'),
        ('team_management', '0006_shiftpattern_employees_shiftpattern_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftpattern',
            name='employees',
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='shift_patterns', to='accounts.employee'),
        ),
    ]
