# Generated by Django 5.0.6 on 2024-06-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0007_remove_shiftpattern_employees_shiftpattern_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='shiftblock',
            name='working_dates',
            field=models.ManyToManyField(related_name='shift_blocks', to='team_management.date'),
        ),
        migrations.DeleteModel(
            name='ShiftAssignment',
        ),
    ]
