# Generated by Django 5.0.6 on 2024-06-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_created_at_company_modified_at_and_more'),
        ('team_management', '0008_date_shiftblock_working_dates_delete_shiftassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftpattern',
            name='employees',
            field=models.ManyToManyField(related_name='shift_patterns', to='accounts.employee'),
        ),
    ]
