# Generated by Django 5.0.6 on 2024-06-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0009_alter_shiftpattern_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='shiftblock',
            name='working_dates',
            field=models.ManyToManyField(blank=True, related_name='shift_blocks', to='team_management.date'),
        ),
    ]
