# Generated by Django 5.0.6 on 2024-06-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0010_alter_date_date_alter_shiftblock_working_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftpattern',
            name='employees',
        ),
    ]
