# Generated by Django 5.0.6 on 2024-06-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0011_remove_shiftpattern_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftpattern',
            name='manager',
        ),
    ]
